### ISSUE TITLE
improvement: rank display

### ISSUE THREAD

**Issue by alexuk79** [Ja-Sa-La/League-Account-Manager#10]
Hi, is it possible to add number of division after PullData?
Example: Silver IV (or Silver 4) with: 3 wins and 4 losses
![image](https://github.com/Ja-Sa-La/League-Account-Manager/assets/132964641/73b8a747-7dbb-483f-bbea-3f46814f9ec8)

**Comment by Ja-Sa-La** [comment]
Panning At somepoint reworking ranked displays, busy with actual work ATM.

**Comment by Ja-Sa-La** [comment]
@alexuk79 Ranked display has now been updated in the latest release, any feedback?

**Comment by Ja-Sa-La** [comment]
most likely not, it's not really meant for mass checking accounts. if you wanted to do that there are other programs for it
