### ISSUE TITLE
Need a nudge to help make an anti autofill

### ISSUE THREAD

**Issue by godmode1111** [Ja-Sa-La/League-Account-Manager#11]
Hi again,

I learnt of a method where you can stop queue 30 seconds or so before the estimated time and requeue and this heavily reduces chance secondary and auto fill. I was wanting to add this to your program but as I've said before I'm not too familiar with c# and I'm finding it a little difficult to find what I'm looking for to find: "time since queuing" and the "estimated queue time". I know I'm looking for something within Page10.xaml.cs. I was just looking for a nudge in the right direction to find the private fields or methods would give me what I'm looking for.

**Comment by godmode1111** [comment]
after i was also wanting to have a crack to revamp it to be more like this btw: 
![image](https://github.com/Ja-Sa-La/League-Account-Manager/assets/65020937/335c37b1-6104-4d94-a8b2-5b076ccd59cd)

**Comment by godmode1111** [comment]
When semesters over I'm also going to try to make it something like this:
![image](https://github.com/Ja-Sa-La/League-Account-Manager/assets/65020937/5072cf25-ff0c-49d4-939b-5187f77ce058)
does this sound good to you?

**Comment by Ja-Sa-La** [comment]
Hello, i think this be easier to chat about this via discord, you can add me j.s.l
