### ISSUE TITLE
Notes for account

### ISSUE THREAD

**Issue by esbe1175** [Ja-Sa-La/League-Account-Manager#13]
Yo! Been using this every day almost, awesome tool. Just one feature i would like to request

A custom "notes" column would be awesome, with an interface similar to the champions/skins/loot ones, but editable and without a search bar. Nice to be able to note things about specific accounts (like keeping track of which accounts you need to do X thing on, for example).

**Comment by Ja-Sa-La** [comment]
would be nice to add yeah, been busy with other project but might add it at some point.

**Comment by Ja-Sa-La** [comment]
This has now been added, just double click the "Open" on notes column of account list

**Comment by esbe1175** [comment]
My man 🤝
