### ISSUE TITLE
Version Mismatch: AssemblyInfo.cs still reflects version 2.1.0.5 instead of 2.1.0.6

### ISSUE THREAD

**Issue by Ku-Tadao** [Ja-Sa-La/League-Account-Manager#16]
**Describe the bug**  
When downloading the latest release (2.1.0.6) of League Account Manager, the `AssemblyInfo.cs` file (found [here](https://github.com/Ja-Sa-La/League-Account-Manager/blob/master/League_Account_Manager/AssemblyInfo.cs)) still lists the version as 2.1.0.5. This causes a mismatch between the version in the source code and the official release version.

**To Reproduce**  
1. Download the latest release (2.1.0.6) source code from the repository.
2. Open the `League_Account_Manager/AssemblyInfo.cs` file ([direct link](https://github.com/Ja-Sa-La/League-Account-Manager/blob/master/League_Account_Manager/AssemblyInfo.cs)).
3. Observe that the version number is still set to 2.1.0.5.

**Expected behavior**  
The version number in `AssemblyInfo.cs` should be updated to 2.1.0.6 to match the release version, ensuring consistency.

**Screenshots**  
_No screenshots needed for this issue._

**Desktop (please complete the following information):**
- OS: [e.g. Windows 11]
- Version: [e.g. 2.1.0.6]

**Log File:**  
_No logs required for this issue._

**Additional context**  
This discrepancy in version numbers causes confusion, even though the repository itself is up to date. The mismatch lies within the assembly info file, which hasn’t been updated to reflect version 2.1.0.6.

**Comment by Ja-Sa-La** [comment]
Yeah i was just too lazy push the changes. They are now there
