### ISSUE TITLE
Since patch, no longer enters account information into the boxes.

### ISSUE THREAD

**Issue by esbe1175** [Ja-Sa-La/League-Account-Manager#2]
The rest of the functions seem to be working as usual.

same as #1

**Comment by Ja-Sa-La** [comment]
hmm, I'm unable to recreate this issue with [latest release](https://github.com/Ja-Sa-La/League-Account-Manager/releases/tag/1.0.0.17) can you double-check the version you are running? also, are you running a different language riot client from English?
@esbe1175

**Comment by Ja-Sa-La** [comment]
was able to reproduce the issue with a friend, fixed & you can now download [new release](https://github.com/Ja-Sa-La/League-Account-Manager/releases/tag/1.0.0.18)

**Comment by esbe1175** [comment]
Thanks! works perfectly again.
