### ISSUE TITLE
 It stops working when I log in

### ISSUE THREAD

**Issue by efsanevidemir** [Ja-Sa-La/League-Account-Manager#4]
![Ekran Alıntısı](https://github.com/Ja-Sa-La/League-Account-Manager/assets/83442695/99d0be6e-1db9-4265-8b82-7cafa781fb19)

When I enter my account information and click the "Login" button, I get an error that it has stopped working.

**Comment by Ja-Sa-La** [comment]
are you running it as an admin? @efsanevidemir

**Comment by efsanevidemir** [comment]
I run it as an administrator and the directory where the game is installed is in the default folder. On my first try, it didn't work, the same error over and over again.

**Comment by efsanevidemir** [comment]
> Are you running it as an admin? Do you know if your League of Legends install location is the default one? Did you make any changes since it seems like it worked before? @efsanevidemir

Hi dude, again, I installed the latest update and it is now working without any problems, thank you
