### ISSUE TITLE
Fills information, but won't press the login button.

### ISSUE THREAD

**Issue by esbe1175** [Ja-Sa-La/League-Account-Manager#5]
It seems like a client update has caused some issues.

Currently when you press Login on the account manager interface, it correctly launches the riot client, enters the information and then gets stuck cycling between the two input boxes, never pressing login. This also causes the account manager to seize up and your only option is to kill the process, at which point you can manually press login.

**Comment by esbe1175** [comment]
I'm using the latest version. I don't think the server matters, I'm in between EUNE/EUW/TR servers mostly.
Let me try fully wiping and adding one account just to test.

**Comment by esbe1175** [comment]
Completely fresh install, only one, real, account added and it still does it.

**Comment by Ja-Sa-La** [comment]
hmm i will try adding another login method should have an update within few hours

**Comment by Ja-Sa-La** [comment]
@esbe1175 when you have the time, test out login v2 should work for now.

**Comment by esbe1175** [comment]
Works perfectly. Hope it continues to work for a good while 🫡🔥
