### ISSUE TITLE
Question: Anything here bannable?

### ISSUE THREAD

**Issue by tsarsa54215215** [Ja-Sa-La/League-Account-Manager#7]
Hello, was wondering if features like mass-reporting, quick champ buy are bannable? Can I get flagged somehow?

**Comment by Ja-Sa-La** [comment]
Haven't gotten any bans, everything LAM does is what league & riotclient does already, worst case you get ratelimited and have to wait few seconds. Only way to get banned is if you advertice that you know other peoples usernames in champ select and another player decies to ticket you.
