### ISSUE TITLE
Crash when pulldata or delete

### ISSUE THREAD

**Issue by godmode1111** [Ja-Sa-La/League-Account-Manager#8]
The expected output still goes through but the manager just quits. 

Same issue when I built the program myself and from the release.

Is there a crash log?

**Comment by Ja-Sa-La** [comment]
The issue template that you decided to overwrite and not follow quite literally asks you to send in the logs, called log.txt...

**Comment by godmode1111** [comment]
oh my bad. well either way it didn't spit anything back out into log.txt

**Comment by Ja-Sa-La** [comment]
Hmm considering that it crashes on those 2 steps it sounds like LAM is unable to write to the account list file. Have you tried restarting you PC if something else has locked the file that should resolve it.

**Comment by Ja-Sa-La** [comment]
Figured out that I had made a mistake and UI was being updated from wrong thread, issue is now fixed on on latest release. Can you please confirm if it is now working for you too, thanks for reporting

https://github.com/Ja-Sa-La/League-Account-Manager/releases/tag/2.0.0.16

**Comment by Ja-Sa-La** [comment]
I will push the change at somepoint, for now modify this function in page1.xaml.cs


    private async void OnChanged(object source, FileSystemEventArgs e)
    {
        await loaddata();
        Dispatcher.Invoke(() =>
            { 
Championlist.Items.SortDescriptions.Add(new SortDescription("level", ListSortDirection.Descending));
        Championlist.Columns[12].Visibility = Visibility.Collapsed;
        Championlist.Columns[8].Visibility = Visibility.Collapsed;
        Championlist.Columns[9].Visibility = Visibility.Collapsed;

});

    }

**Comment by godmode1111** [comment]
thanks <3
